USER_NOT_FOUND 											= 1001
DEVICE_DOES_NOT_BELONG_TO_USER 							= 1002

DEVICE_NOT_FOUND 										= 2001
REGISTRATION_ID_NOT_FOUND								= 2002
REGISTRATION_DETAIL_NOT_FOUND							= 2003
REGISTRATION_DETAIL_EXPIRES								= 2004
APP_UNIQUE_ID_NOT_FOUND									= 2005
PLATFORM_ENDPOINT_NOT_FOUND								= 2006
DEVICE_EVENT_CODE_NOT_FOUND 							= 2007
PARENT_DEVICE_NOT_FOUND									= 2008
	
INVALID_DEVICE_ACCESSIBILITY_MODE 						= 3001
INVALID_IP_ADDRESS_FORMAT 								= 3002
INVALID_CAPABILITY_FORMAT 								= 3003
INVALID_FIRMWARE_FORMAT 								= 3004
INVALID_DEVICE_SETTING_KEY 								= 3005
INVALID_DEVICE_SETTING_VALUE							= 3006
INVALID_DEVICE_SETTINGS_FORMAT							= 3007
DEVICE_LOCATION_NOT_UPDATED 							= 3008
INVALID_APP_SETTINGS_FORMAT								= 3009
INVALID_DATETIME_FORMAT                   = 3010

INVALID_MODEL 											= 4001
INVALID_EMAIL_FORMAT 									= 4002
INVALID_EMAIL_TYPE 										= 4003
INVALID_DEVICE_TYPE 									= 4004
INVALID_CLIENT_TYPE 									= 4006
MODE_NOT_SUPPORTED 										= 4007
INVALID_ALERT_FORMAT 									= 4008

ERROR_SENDING_COMMAND 									= 5001
ERROR_ACTIVE_RECORD 									= 5002
ERROR_GENERAL_VALIDATION 								= 5003
ERROR_JSON_FORMAT 										= 5004
REMOTE_IP_NULL 											= 5005
REMOTE_PORT_NULL 										= 5006
INVALID_DEVICE_TOKEN 									= 5007
INVALID_URI 											= 5008
CONNECTION_REFUSED 										= 5009

APP_DOES_NOT_BELONG_TO_USER 							= 6001
INVALID_APP_TYPE 										= 6002
INVALID_CERT_TYPE										= 6003

ERROR_RECURLY_ACCOUNT_NOT_FOUND							= 7001
ERROR_RECURLY_SUBSCRIPTION								= 7002
ERROR_RECURLY_SUBSCRIPTION_NOT_FOUND					= 7003
ERROR_RECURLY_SUBSCRIPTION_EXPIRED						= 7004

INVALID_FILTER_SYNTAX 									= 8001
INVALID_FILTER_VALUE									= 8002

TIMEOUT_ERROR 											= 9001
UNABLE_TO_CREATE_SESSION 								= 9002
UNABLE_TO_CREATE_FILE_SESSION							= 9003
ROUTING_ERROR 											= 9097
IMPLEMENTATION_PENDING 									= 9098
UNDEFINED_ERROR_CODE 									= 9099
TYPE_NOT_FOUND                                          = 9101
MODEL_NOT_FOUND                                         = 9102
INVALID_FILE											= 9110
IO_ERROR                                                = 9103
TOKEN_ALREADY_USED										= 9104
INVALID_PARAMETER                                       = 9105
DEVICE_INACTIVE											= 9106
RECURLY_EXCEPTION										= 9107
DEVICE_MODEL_IN_USE 									= 9108
DEVICE_TYPE_IN_USE										= 9109
INVALID_REQUEST											= 9110
RECURLY_ERROR											= 9111
PLAN_NOT_FOUND											= 9112
INVALID_TOKEN                                           = 9113
CANNOT_DOWNGRADE										= 9114
DEVICE_TEST_BATCH_NOT_FOUND								= 9115
MAC_ADDRESS_NOT_FOUND_IN_DEVICE_MASTER					= 9116
DEVICE_NOT_AVAILABLE									= 9117
DEVICE_INVITATION_NOT_FOUND								= 9118
IVITATION_NOT_FOR_CURRENT_USER							= 9119
INVALID_REGISTRATION_ID									= 9120
TYPE_ERROR												= 9121
RELAY_SESSION_NOT_FOUND									= 9122
INVALID_PARAMETER_LENGTH								= 9133
ENTITY_NOT_FOUND										= 9134
DATABASE_VALIDATION_ERROR								= 9135
DEVICE_FREE_TRIAL_CLAIMED								= 9136

UPLOADING_FAIL 											= 600
INVALID_COMMAND_PASSED 									= 601
PARAMETER_MISSING 										= 602
PARAMETER_LENGTH_OUT_OF_BOUND 							= 603
INVALID_PARAMETER_FORMAT 								= 604
#INVALID_EMAIL_FORMAT 									= 606
CAMERA_NOT_EXIST 										= 611
CAMERA_NOT_ACCESSIBLE 									= 612
CANNOT_COMMUNICATE_WITH_CAMERA 							= 613
CAMERA_NOT_AVAILABLE 									= 614
EMAIL_NOT_REGISTERED									= 621
EMAIL_ID_REGISTERED_NOT_ACTIVATED 						= 622
EMAIL_ID_ALREADY_ACTIVATED 								= 623
ACTIVATION_FAILED 										= 624
ACTIVATION_FAILED_INVALID_KEY 							= 625
AUTHENTICATION_FAILED 									= 626
CAMERA_NOT_ASSOCIATED 									= 627
USER_REGISTRATION_FAILED 								= 628
STREAMING_PORT_CLOSED 									= 629
IMAGE_NOT_EXIST 										= 630
REDO_PORT_FORWARDING 									= 631
CAMERA_ACCESS_PROBLEM 									= 632
UPNP_REQUEST_SENT 										= 635
USERNAME_ALREADY_REGISTERED 							= 636
INVALID_ACCESS 											= 637
FILE_NOT_UPLOADED 										= 638
UNABLE_TO_DELETE_DIRECTORY 								= 639
UNMAPPED_MACADDRESS 									= 640
INVALID_IMAGE_FORMAT 									= 641
INVALID_IP_ADDRESS 										= 642
INVALID_PORT 											= 643
UNKNOWN_HOST 											= 644
CAMERA_NOT_ASSOCIATED_USER 								= 645
ERROR_GETTING_RELAY_SERVER 								= 646
INVALID_TEMPERATURE_UNIT 								= 647
UNABLE_TO_UPDATE_DB 									= 648
UNABLE_TO_CONNECT_TO_RELAY_SERVER 						= 649
UNHANDLED_EXCEPTION 									= 699
UNAUTHORIZED_ACCESS 									= 401
UPNP_REQUEST 											= 801
SNAPSHOT_REQUEST 										= 802
UPNP_AND_SNAPSHOT_REQUEST 								= 803
SESSION_MISMATCH 										= 851


SUCCESS 												= 200
PARAMETERS_INSUFFICIENT 								= 400
CAMERA_NOT_REGISTERED_IN_PORTAL 						= 401
CAMERA_NOT_CONNECTED 									= 701
CAMERA_BUSY_OR_NOT_AVAILABLE 							= 702
INTERNAL_STUN_CLIENT_ERROR 								= 703
INTERNAL_STUN_SERVER_ERROR 								= 704 
COMMUNICATION_ERROR_WITH_PORTAL 						= 705
SERVER_NOT_REACHABLE_OR_NOT_STARTED 					= 706
STREAMID_NOT_EXIST 										= 707
ILLEGAL_OPERATION_REQUEST 								= 708
CAMERA_DISCONNECTED 									= 709
INVALID_COMMAND_RESPONSE 								= 710


# HTTP Status code
HTTP_CLIENT_CONFLICT_ERROR_CODE							= 409


























