# config/application.yml
defaults: &defaults
  google_analytics_tracker: 'UA-42360587-1' # a/c: mahesh.sapre@connovatech.com
  google_analytics_domain: "api.simplimonitor.com"
  api_server_url: "api.monitoreverywhere.com"


  aws_access_key_id: "AKIAIDBFDZTAR2EB4KPQ" 
  aws_secret_access_key: "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" 
  s3_bucket_name: "localhost-resources"
  s3_devices_path: "devices/%s/%s"
  s3_events_path: "devices/%s/%s/%s"
  s3_event_snap_path: "devices/%s/snaps/%s"
  s3_event_clip_path: "devices/%s/clips/%s"
  s3_logs_path: "devices/%s/logs/%s"
  s3_device_masters_path: "device_models/%s/device_masters"
  s3_device_model_capabilities_path: "device_models/capabilities/%s" 
  s3_device_types_capabilities_path: "device_types/capabilities/%s"
  s3_test_report_bucket: "factory_test_report"
  s3_device_folder: "devices/%s"
  file_path: "files/images/settings.PNG" 
  snaps_path: "snaps"
  clips_path: "clips"
  logs_path: "logs"
  logo_baby_path: "images/logo-baby.png"
  aws_max_retries: 10
  location_directory: "files/location"
  capabiltity_directory: "files/capability"

  hours_inactive: "1440"
  deactivate_after: "72"
  hours_stored: "1440"
  wait_for: "72"
  days_crossed: "7"

  default_page_size : 10
  iv_length: 16
  motion_detected: 4

    

  exception_notifier:
    sender: "noreply@monitoreverywhere.com"
    recepient: "kavya.vj@connovatech.com"

  registration_id_length: 26
  mac_address_length: 12  

  sns_platform_endpoint:
    gcm: "arn:aws:sns:us-east-1:477584755503:app/GCM/sm_gcm_app"
    apns: "arn:aws:sns:us-east-1:477584755503:app/APNS_SANDBOX/sm_apns"  

  catergory_users: "Users"  
  catergory_devices: "Devices"  

  time_out:
    is_port_open_timeout: 10
    portal_agent_timeout: 25
    device_available_timeout: 10
    trigger_subclip_timeout: 10
    create_subscription_timeout: 10
    server_status_timeout: 3
    wowza_server_timeout: 10

    deactivation_message: "The device has not been used for last 60 days. It will be inactivated after 3 days."
    upgrade_message: "Please upgrade the subscription_type"
    invalid_format_message: "Has invalid format"

  stun:
    byte_array : [0, 1, 0, 52, 33, 18, 164, 66, 166, 112, 219, 208, 115, 238, 5, 179, 21, 127, 39, 138, 128, 52, 0, 4, 116, 114, 117, 101, 0, 6, 0, 12, 52, 52, 51, 51, 52, 67, 51, 49, 65, 48, 48, 67, 128, 46, 0, 5, 116, 104, 114, 101, 101, 0, 0, 0, 128, 48, 0, 12, 52, 52, 51, 51, 52, 67, 51, 49, 65, 48, 48, 67]
    stun_1_2_byte_array : [0,1,0,8,-48,-73,25,16,116,-24,126,70,54,-59,58,101,-105,4,26,90,0,3,0,4,0,0,0,0]
    response_maxlen : 100

  wowza_server:
    get_dvr_list: "http://wowza.simplimonitor.com:8086/wowzaservice?app=camera&action=get_dvr_list&macAddress=%s"
  
  send_command_url: "%sSendCommandEncrypted?macaddress=%s&channelId=%s&command=%s"
  get_remote_ip_url: "%sGetRemoteIP?macaddress=%s"
  
  rtmp_url: "rtmp://%s:%s/camera/mp4:%s.stream"
  relay_rtmp_url: "rtmp://%s:%s/%s"
  p2p_upnp_rtsp_url: "rtsp://%s:%s@%s:%s/blinkhd" #"rtsp://﻿﻿<registration_id>:<session_key>@<cam_remote_ip>:<cam_remote_port_1>/blinkhd"
  
  from: "noreply@monitoreverywhere.com"
  address: "email-smtp.us-east-1.amazonaws.com"
  port: 25
  domain: "monitoreverywhere.com"
  user_name: "AKIAJWHMJGOXGIGVVJJQ"
  password: "AtA2+MQvRVy+cBWLFiSEGhnlSwDXbzPHjDJrm+EJ0Y6b"

  facebook_app_id: "660742193968789"
  facebook_app_secret: "0cf502caeb2a267f265c59fc6c5949c9"

  channel_id: "123456789012"
  cipher_decryption_exception: "Data not multiple of block length.Got non-encrypted message"
  invalid_format_message: "Has invalid format"

  urls:
    stun_server: "stun.simplimonitor.com" 
    stun1_server: "stun1.simplimonitor.com"
    stun2_server: "stun2.simplimonitor.com"
    wowza_server: "http://ct-wowza.hubble.in"
    wowza_http_port: "1935"
    portal_agent: "http://stun.hubble.in/PortalAgentWrapper/"
    upload_server: "http://upload1.simplimonitor.com/"

  wowza_rtmp_port: "1935"
  
  camera_commands:
    set_subscription_plan_command: "action=command&command=set_subscription_plan&value=%s"
    downgrade_streaming_video_quality: "action=command&command=video_quality&value=2"
    check_camera_ready_command: "action=command&command=check_cam_ready"
    get_session_key_mode_any_command: "action=command&command=get_session_key&mode=any"
    get_session_key_mode_rtmp: "action=command&command=get_session_key&mode=relay_rtmp"
    close_session_command: "action=command&command=close_relay_rtmp"

  reset_password_portal_url: "connovatech.com/api-test-portal/reset_password.html" 
  device_share_url: "https://hubble.in"
  email_sent_message: "email sent"
  share_with_mail_not_same: "Email id of user not same as the shared email id"

  secret_token: "9e3c63bd23a0f59dd97ba9a3032fbb9c4fdb5235ce0c14dba7a611b3516f66a693ce727efef552ac66489423fd99d27e8a5ba1489ab06adc43c2a192621ba066" 

  camera_service:
    update_port_info_response: "Port information updated successfully."
    set_stream_mode_response: "Sucessfully updated Streaming mode"
    port_open_response: "Port %s is open on %s."
    port_closed_response: "Port %s is closed on %s."
    version_upgrade_response: "Sucessful version upgradation"
    set_access_token_response: "Successfully updated access token"
    notification_response: "Received notification from camera.\n
      <br/>\n
      Found users with enabled alert settings:%s \n
      <br/>\n
      Sending notification to devices: \n
      <br/>\n
      GCMDevices:%s \n
      <br/>\n
      IOSDevices:%s"
    upate_ip_response: "Successful update \n
      <br/> \n
      IP Address=%s \n
      <br/> \n
      MacAddr=%s \n
      <br/> \n
      Local IP=%s \n"


development:
  <<: *defaults
  neat_setting: 800
  error_docs_url: "http://api.simplimonitor.com/errors/%s" 

test:
  <<: *defaults
  error_docs_url: "http://simplimonitor.com/errors/%s"

  aws_access_key_id: "<%= ENV['AWS_ACCESS_KEY_ID'] %>"
  aws_secret_access_key: "<%= ENV['AWS_SECRET_KEY'] %>"

  sns_platform_endpoint:
    gcm: "<%= ENV['GCM_ENDPOINT'] %>"
    apns: "<%= ENV['APNS_ENDPOINT'] %>"
 

production:
  <<: *defaults
  google_analytics_tracker: 'UA-41698182-1'
  error_docs_url: "http://monitoreverywhere.com/errors/%s"

  aws_access_key_id: "<%= ENV['AWS_ACCESS_KEY_ID'] %>"
  aws_secret_access_key: "<%= ENV['AWS_SECRET_KEY'] %>"

  iam_role: "<%= ENV['IAM_ROLE'] %>"

  sns_platform_endpoint:
    gcm: "<%= ENV['GCM_ENDPOINT'] %>"
    apns: "<%= ENV['APNS_ENDPOINT'] %>"

  exception_notifier:
    sender: "noreply@monitoreverywhere.com"
    recepient: "<%= ENV['EXCEPTION_NOTIFIER_RECIPIENT'] %>"

  urls:
    stun_server: "<%= ENV['URL_STUN_SERVER'] %>" 
    stun1_server: "<%= ENV['URL_STUN1_SERVER'] %>"
    stun2_server: "<%= ENV['URL_STUN2_SERVER'] %>"
    wowza_server: "<%= ENV['URL_WOWZA_SERVER'] %>"
    wowza_http_port: "<%= ENV['WOWZA_HTTP_PORT'] %>"
    portal_agent: "<%= ENV['URL_PORTAL_AGENT'] %>"
    upload_server: "<%= ENV['URL_UPLOAD_SERVER'] %>"

  hours_inactive: "<%= ENV['HOURS_INACTIVE'] %>"
  deactivate_after: "<%= ENV['DEACTIVATE_AFTER'] %>"
  hours_stored: "<%= ENV['HOURS_STORED'] %>"
  wait_for: "<%= ENV['WAIT_FOR'] %>" 
  days_crossed: "<%= ENV['DAYS_CROSSED'] %>" 

  reset_password_portal_url: "<%= ENV['RESET_PASSWORD_PORTAL_URL'] %>"

  facebook_app_id: "<%= ENV['FACEBOOK_APP_ID'] %>" 
  facebook_app_secret: "<%= ENV['FACEBOOK_APP_SECRET'] %>" 

  s3_bucket_name: "<%= ENV['S3_BUCKET_NAME'] %>" 
  wowza_rtmp_port: "<%= ENV['WOWZA_RTMP_PORT'] %>"

  secret_token: "<%= ENV['SECRET_TOKEN'] %>" 
